## 数据集归一化与反归一化

In [1]:
import numpy as np

In [2]:
a = np.array([[4, 40, 32], [20, 3, 7], [30, 25, 9]])

In [3]:
def Zero_To_One(data):
    min = np.min(data, axis=0)
    max = np.max(data, axis=0)    
    return (data-min) / (max - min), min, max 

b, m, n = Zero_To_One(a)
print(b)
print(m)

[[0.         1.         1.        ]
 [0.61538462 0.         0.        ]
 [1.         0.59459459 0.08      ]]
[4 3 7]


In [4]:
# 反归一化
def back_To_origin(data, min, max):
    return data*(max-min) + min

c = back_To_origin(b, m, n)
print(c)

[[ 4. 40. 32.]
 [20.  3.  7.]
 [30. 25.  9.]]


In [22]:
import torch
from torch.utils.data import DataLoader

data = torch.Tensor(b).to(torch.float64)
dataload = DataLoader(data, batch_size=1)

In [23]:
item = []
for x in dataload:
    item.append(back_To_origin(x,m,n).squeeze().numpy())
    print(item)
nn = np.stack(item)

[array([ 4., 40., 32.])]
[array([ 4., 40., 32.]), array([20.0000006,  3.       ,  7.       ])]
[array([ 4., 40., 32.]), array([20.0000006,  3.       ,  7.       ]), array([30.        , 25.00000012,  8.99999996])]


In [24]:
print(nn)

[[ 4.         40.         32.        ]
 [20.0000006   3.          7.        ]
 [30.         25.00000012  8.99999996]]


## Matplotlib

In [1]:
import matplotlib.pyplot as plt